import { Term, Listing } from './types';

export const terms = new Listing({
  'eof': new Term('EOF'),
  'eps': new Term('EPS'),
  'id': new Term('ID'),
  'num': new Term('NUM'),
  'int': new Term('INT'),
  'void': new Term('VOID'),
  'continue': new Term('CONT'),
  'break': new Term('BREAK'),
  'if': new Term('IF'),
  'else': new Term('ELSE'),
  'while': new Term('WHILE'),
  'return': new Term('RET'),
  'switch': new Term('SWITCH'),
  'case': new Term('CASE'),
  'default': new Term('DEF'),
  '{': new Term('{'),
  '}': new Term('}'),
  '(': new Term('('),
  ')': new Term(')'),
  '[': new Term('['),
  ']': new Term(']'),
  ',': new Term(','),
  ';': new Term(';'),
  ':': new Term(':'),
  '=': new Term('='),
  '<': new Term('<'),
  '+': new Term('+'),
  '-': new Term('-'),
  '*': new Term('*'),
});

export const rules = new Listing({
  'program': [['declaration-list', terms.get('eof')]],
  'declaration-list': [['declaration-list', 'declaration'], [terms.get('eps')]],
  'declaration': [['var-declaration'], ['fun-declaration']],
  'var-declaration': [['type-specifier', terms.get('id'), terms.get(';')], ['type-specifier', terms.get('id'), terms.get('['), terms.get('num'), terms.get(']'), terms.get(';')]],
  'type-specifier': [[terms.get('int')], [terms.get('void')]],
  'fun-declaration': [['type-specifier', terms.get('id'), terms.get('('), 'params', terms.get(')'), 'compound-stmt']],
  'params': [['param-list'], [terms.get('void')]],
  'param-list': [['param-list', terms.get(','), 'param'], ['param']],
  'param': [['type-specifier', terms.get('id')], ['type-specifier', terms.get('id'), terms.get('['), terms.get(']')]],
  'compound-stmt': [[terms.get('{'), 'declaration-list', 'statement-list', terms.get('}')]],
  'statement-list': [['statement-list', 'statement'], [terms.get('eps')]],
  'statement': [['expression-stmt'], ['compound-stmt'], ['selection-stmt'], ['iteration-stmt'], ['return-stmt'], ['switch-stmt']],
  'expression-stmt': [['expression', terms.get(';')], [terms.get('continue'), terms.get(';')], [terms.get('break'), terms.get(';')], [terms.get(';')]],
  'selection-stmt': [[terms.get('if'), terms.get('('), 'expression', terms.get(')'), 'statement', terms.get('else'), 'statement']],
  'iteration-stmt': [[terms.get('while'), terms.get('('), 'expression', terms.get(')'), 'statement']],
  'return-stmt': [[terms.get('return'), terms.get(';')], [terms.get('return'), 'expression', terms.get(';')]],
  'switch-stmt': [[terms.get('switch'), terms.get('('), 'expression', terms.get(')'), terms.get('{'), 'case-stmts', 'default-stmt', terms.get('}')]],
  'case-stmts': [['case-stmts', 'case-stmt'], [terms.get('eps')]],
  'case-stmt': [[terms.get('case'), terms.get('num'), terms.get(':'), 'statement-list']],
  'default-stmt': [[terms.get('default'), terms.get(':'), 'statement-list'], [terms.get('eps')]],
  'expression': [['var', terms.get('='), 'expression'], ['simple-expression']],
  'var': [['additive-expression', 'relop', 'additive-expression'], ['additive-expression']],
  'relop': [[terms.get('<')], [terms.get('='), terms.get('=')]],
  'additive-expression': [['additive-expression', 'addop', 'term'], ['term']],
  'addop': [[terms.get('+')], [terms.get('-')]],
  'term': [['term', terms.get('*'), 'signed-factor'], ['signed-factor']],
  'signed-factor': [['factor'], [terms.get('+'), 'factor'], [terms.get('-'), 'factor']],
  'factor': [[terms.get('('), 'expression', terms.get(')')], ['var'], ['call'], [terms.get('num')]],
  'call': [[terms.get('id'), terms.get('('), 'args', terms.get(')')]],
  'args': [['arglist'], [terms.get('eps')]],
  'arg-list': [['arglist', terms.get(','), 'expression'], ['expression']]
});
